# Initial Data Analysis - Capstone Project

In [5]:
# Imports
import os
import csv
import numpy as np
import pandas as pd
from pandas import Int64Index
import pickle
import sys

In [6]:
def save_as_pkl(object, path):
	pickle.dump(object, open(path, "wb"))

def load_pkl(path):
	obj = pickle.load(open(path, "rb"))
	return obj

### Preprocessing and loading the data

In [7]:
# Processing the .csvs into dataframes and saving them as pickles for easier
# loading on future runs
files = [f for f in os.listdir("data/") if f.split('1')[0] == 'file']
for file in files:
    print ('\n'+file)
    fName = file.split('.')[0]
    df = pd.read_csv('data/' + file, delimiter=',', na_values=['NA'])
#     df["Id"] = df.reset_index().index
#     df.set_index("Id")
    print(df.shape)
    save_as_pkl(df, 'pickles/'+fName+'.pkl')

file10.csv
      YEAR   RECNO  SCHOOL  SBOARD  REGBOARD  CNTYBOARD  GEND  BIRTHY  \
0     2010  831401   11219    7010    6007.0     5007.0   119    1993
1     2010  831400   11219    7010    6007.0     5007.0   119    1994
2     2010  831393   11219    7010    6007.0     5007.0   120    1992
3     2010  831391   11219    7010    6007.0     5007.0   120    1992
4     2010  831438   11219    7010    6007.0     5007.0   120    1992
...    ...     ...     ...     ...       ...        ...   ...     ...
3974  2010  800164   11023    7022    6005.0     5005.0   120    1992
3975  2010  800159   10476    7043    6032.0     5032.0   120    1990
3976  2010  800237   11141    7007    6024.0     5024.0   120    1992
3977  2010  800231   10880    7051    6021.0     5021.0   120    1992
3978  2010  800228   10949    7044    6031.0     5031.0   120    1991

      RESPROV  RESCNTY  ... DMAJ20  DCOOP20  DLEV20  UDEC20  PRO20  PRGO20  \
0         125      137  ...    NaN      NaN     NaN     NaN    NaN     300
1         125      137  ...    NaN      NaN     NaN     NaN    NaN     300
2         125      137  ...    NaN      NaN     NaN     NaN    NaN     300
3         125      137  ...    NaN      NaN     NaN     NaN    NaN     300
4         125      137  ...    NaN      NaN     NaN     NaN    NaN     300
...       ...      ...  ...    ...      ...     ...     ...    ...     ...
3974      125      135  ...    NaN      NaN     NaN     NaN    NaN     300
3975      125      164  ...    NaN      NaN     NaN     NaN    NaN     300
3976      125      143  ...    NaN      NaN     NaN     NaN    NaN     300
3977      125      153  ...    NaN      NaN     NaN     NaN    NaN     300
3978      125      163  ...    NaN      NaN     NaN     NaN    NaN     300

      DENRD20  DLEVD20  CONIND20 REGIND20
0         NaN      NaN       NaN      NaN
1         NaN      NaN       NaN      NaN
2         NaN      NaN       NaN      NaN
3         NaN      NaN       NaN      NaN
4         NaN      NaN       NaN      NaN
...       ...      ...       ...      ...
3974      NaN      NaN       NaN      NaN
3975      NaN      NaN       NaN      NaN
3976      NaN      NaN       NaN      NaN
3977      NaN      NaN       NaN      NaN
3978      NaN      NaN       NaN      NaN

[3979 rows x 392 columns]

file11.csv
      YEAR   RECNO  SCHOOL  SBOARD  REGBOARD  CNTYBOARD  GEND  BIRTHY  \
0     2011  831466   11219    7010    6007.0     5007.0   119    1993
1     2011  831464   10942    7009    6053.0     5053.0   120    1992
2     2011  831459   11148    7007    6014.0     5014.0   120    1992
3     2011  831456   11238    7010    6032.0     5032.0   120    1990
4     2011  831398   10246    7007    6013.0     5013.0   120    1991
...    ...     ...     ...     ...       ...        ...   ...     ...
3953  2011  800128   10692    7043    6032.0     5032.0   120    1993
3954  2011  800125   10315    7005       NaN        NaN   120    1990
3955  2011  800126   11199    7010    6032.0     5032.0   120    1994
3956  2011  800087   10530    7020    6007.0     5007.0   120    1990
3957  2011  800056   10345    7007    6013.0     5013.0   120    1993

      RESPROV  RESCNTY  ... DMAJ20  DCOOP20  DLEV20  UDEC20  PRO20  PRGO20  \
0         125      137  ...    NaN      NaN     NaN     NaN    NaN     300
1         125      185  ...    NaN      NaN     NaN     NaN    NaN     300
2         125      144  ...    NaN      NaN     NaN     NaN    NaN     300
3         125      164  ...    NaN      NaN     NaN     NaN    NaN     300
4         125      143  ...    NaN      NaN     NaN     NaN    NaN     300
...       ...      ...  ...    ...      ...     ...     ...    ...     ...
3953      125      164  ...    NaN      NaN     NaN     NaN    NaN     300
3954      121      147  ...    NaN      NaN     NaN     NaN    NaN     300
3955      125      164  ...    NaN      NaN     NaN     NaN    NaN     300
3956      125      137  ...    NaN      NaN     NaN     NaN    NaN     300
3957      125      143  ...    NaN      NaN     NaN     NaN    NaN     300

      DENRD20  DLEVD20  CONIND20 REGIND20
0         NaN      NaN       NaN      NaN
1         NaN      NaN       NaN      NaN
2         NaN      NaN       NaN      NaN
3         NaN      NaN       NaN      NaN
4         NaN      NaN       NaN      NaN
...       ...      ...       ...      ...
3953      NaN      NaN       NaN      NaN
3954      NaN      NaN       NaN      NaN
3955      NaN      NaN       NaN      NaN
3956      NaN      NaN       NaN      NaN
3957      NaN      NaN       NaN      NaN

[3958 rows x 392 columns]

file12.csv
      YEAR   RECNO  SCHOOL  SBOARD  REGBOARD  CNTYBOARD  GEND  BIRTHY  \
0     2012  831470   11140    7007    6013.0     5013.0   120    1991
1     2012  831471   11140    7007    6013.0     5013.0   120    1993
2     2012  831469   10527    7053    6013.0     5013.0   120    1986
3     2012  831465   11140    7007    6013.0     5013.0   119    1993
4     2012  831459   10321    7005       NaN        NaN   120    1992
...    ...     ...     ...     ...       ...        ...   ...     ...
4281  2012  809096   11224    7007    6014.0     5014.0   120    1992
4282  2012  809093   10345    7007    6013.0     5013.0   120    1993
4283  2012  809085   10583    7053    6013.0     5013.0   120    1992
4284  2012  809079   10599    7053    6013.0     5013.0   119    1994
4285  2012  809081   10434    7027    6014.0     5014.0   119    1992

      RESPROV  RESCNTY  ... DMAJ20  DCOOP20  DLEV20  UDEC20  PRO20  PRGO20  \
0         125      143  ...    NaN      NaN     NaN     NaN    NaN     300
1         125      143  ...    NaN      NaN     NaN     NaN    NaN     300
2         125      143  ...    NaN      NaN     NaN     NaN    NaN     300
3         125      143  ...    NaN      NaN     NaN     NaN    NaN     300
4         121      147  ...    NaN      NaN     NaN     NaN    NaN     300
...       ...      ...  ...    ...      ...     ...     ...    ...     ...
4281      125      144  ...    NaN      NaN     NaN     NaN    NaN     300
4282      125      143  ...    NaN      NaN     NaN     NaN    NaN     300
4283      125      143  ...    NaN      NaN     NaN     NaN    NaN     300
4284      125      143  ...    NaN      NaN     NaN     NaN    NaN     300
4285      125      143  ...    NaN      NaN     NaN     NaN    NaN     300

      DENRD20  DLEVD20  CONIND20 REGIND20
0         NaN      NaN       NaN      NaN
1         NaN      NaN       NaN      NaN
2         NaN      NaN       NaN      NaN
3         NaN      NaN       NaN      NaN
4         NaN      NaN       NaN      NaN
...       ...      ...       ...      ...
4281      NaN      NaN       NaN      NaN
4282      NaN      NaN       NaN      NaN
4283      NaN      NaN       NaN      NaN
4284      NaN      NaN       NaN      NaN
4285      NaN      NaN       NaN      NaN

[4286 rows x 392 columns]

file13.csv
      YEAR   RECNO  SCHOOL  SBOARD  REGBOARD  CNTYBOARD  GEND  BIRTHY  \
0     2013  831446   11219    7010    6007.0     5007.0   119    1995
1     2013  831386   10295    7035    6030.0     5030.0   119    1995
2     2013  831381   10758    7051    6021.0     5021.0   120    1995
3     2013  831437   11225    7007    6014.0     5014.0   120    1995
4     2013  831440   10381    7035    6030.0     5030.0   119    1995
...    ...     ...     ...     ...       ...        ...   ...     ...
4633  2013  809048   11238    7010    6032.0     5032.0   120    1992
4634  2013  809039   10764    7040    6033.0     5033.0   120    1995
4635  2013  809045   10321    7005       NaN        NaN   120    1994
4636  2013  809042   10717    7045    6016.0     5016.0   120    1995
4637  2013  809040   11009    7007    6013.0     5013.0   120    1992

      RESPROV  RESCNTY  ... DMAJ20  DCOOP20  DLEV20  UDEC20  PRO20  PRGO20  \
0         125      137  ...    NaN      NaN     NaN     NaN    NaN     300
1         125      162  ...    NaN      NaN     NaN     NaN    NaN     300
2         125      153  ...    NaN      NaN     NaN     NaN    NaN     300
3         125      144  ...    NaN      NaN     NaN     NaN    NaN     300
4         125      162  ...    NaN      NaN     NaN     NaN    NaN     300
...       ...      ...  ...    ...      ...     ...     ...    ...     ...
4633      125      164  ...    NaN      NaN     NaN     NaN    NaN     300
4634      125      165  ...    NaN      NaN     NaN     NaN    NaN     300
4635      121      147  ...    NaN      NaN     NaN     NaN    NaN     300
4636      125      146  ...    NaN      NaN     NaN     NaN    NaN     300
4637      125      143  ...    NaN      NaN     NaN     NaN    NaN     300

      DENRD20  DLEVD20  CONIND20 REGIND20
0         NaN      NaN       NaN      NaN
1         NaN      NaN       NaN      NaN
2         NaN      NaN       NaN      NaN
3         NaN      NaN       NaN      NaN
4         NaN      NaN       NaN      NaN
...       ...      ...       ...      ...
4633      NaN      NaN       NaN      NaN
4634      NaN      NaN       NaN      NaN
4635      NaN      NaN       NaN      NaN
4636      NaN      NaN       NaN      NaN
4637      NaN      NaN       NaN      NaN

[4638 rows x 392 columns]

file14.csv

      YEAR   RECNO  SCHOOL  SBOARD  REGBOARD  CNTYBOARD  GEND  BIRTHY  \
0     2014  831471   10342    7007    6013.0     5013.0   120    1995
1     2014  831449   11238    7010    6032.0     5032.0   120    1994
2     2014  831453   11140    7007    6013.0     5013.0   120    1994
3     2014  831451   10607    7039    6053.0     5053.0   120    1996
4     2014  831399   10996    7007    6013.0     5013.0   119    1995
...    ...     ...     ...     ...       ...        ...   ...     ...
4831  2014  808960   11138    7007    6013.0     5013.0   120    1995
4832  2014  808959   10342    7007    6013.0     5013.0   120    1996
4833  2014  808966   11142    7007    6013.0     5013.0   120    1996
4834  2014  808962   11154    7007    6024.0     5024.0   120    1995
4835  2014  808958   10345    7007    6013.0     5013.0   120    1995

      RESPROV  RESCNTY  ... DMAJ20  DCOOP20  DLEV20  UDEC20  PRO20  PRGO20  \
0         125      143  ...    NaN      NaN     NaN     NaN    NaN     300
1         121      147  ...    NaN      NaN     NaN     NaN    NaN     300
2         125      143  ...    NaN      NaN     NaN     NaN    NaN     300
3         125      185  ...    NaN      NaN     NaN     NaN    NaN     300
4         121      147  ...    NaN      NaN     NaN     NaN    NaN     300
...       ...      ...  ...    ...      ...     ...     ...    ...     ...
4831      125      143  ...    NaN      NaN     NaN     NaN    NaN     300
4832      125      143  ...    NaN      NaN     NaN     NaN    NaN     300
4833      125      156  ...    NaN      NaN     NaN     NaN    NaN     300
4834      125      144  ...    NaN      NaN     NaN     NaN    NaN     300
4835      125      143  ...    NaN      NaN     NaN     NaN    NaN     300

      DENRD20  DLEVD20  CONIND20 REGIND20
0         NaN      NaN       NaN      NaN
1         NaN      NaN       NaN      NaN
2         NaN      NaN       NaN      NaN
3         NaN      NaN       NaN      NaN
4         NaN      NaN       NaN      NaN
...       ...      ...       ...      ...
4831      NaN      NaN       NaN      NaN
4832      NaN      NaN       NaN      NaN
4833      NaN      NaN       NaN      NaN
4834      NaN      NaN       NaN      NaN
4835      NaN      NaN       NaN      NaN

[4836 rows x 392 columns]

file15.csv
      YEAR   RECNO  SCHOOL  SBOARD  REGBOARD  CNTYBOARD  GEND  BIRTHY  \
0     2015  831468   11064    7047    6014.0     5014.0   120    1996
1     2015  831460   11140    7000    6013.0     5013.0   119    1996
2     2015  831459   11149    7000    6013.0     5013.0   120    1995
3     2015  831458   11140    7000    6013.0     5013.0   120    1997
4     2015  831457   11140    7000    6013.0     5013.0   119    1997
...    ...     ...     ...     ...       ...        ...   ...     ...
5552  2015  809095   10110    7000    6013.0     5013.0   120    1995
5553  2015  809083   10129    7053    6013.0     5013.0   120    1995
5554  2015  809080   10622    7045    6016.0     5016.0   120    1995
5555  2015  809060   10041    7000    6013.0     5013.0   120    1989
5556  2015  809061   10075    7003    6032.0     5032.0   120    1997

      RESPROV  RESCNTY  ... DMAJ20  DCOOP20  DLEV20  UDEC20  PRO20  PRGO20  \
0         125      131  ...    NaN      NaN     NaN     NaN    NaN     300
1         125      143  ...    NaN      NaN     NaN     NaN    NaN     300
2         125      143  ...    NaN      NaN     NaN     NaN    NaN     300
3         125      143  ...    NaN      NaN     NaN     NaN    NaN     300
4         125      143  ...    NaN      NaN     NaN     NaN    NaN     300
...       ...      ...  ...    ...      ...     ...     ...    ...     ...
5552      125      143  ...    NaN      NaN     NaN     NaN    NaN     300
5553      125      143  ...    NaN      NaN     NaN     NaN    NaN     300
5554      125      146  ...    NaN      NaN     NaN     NaN    NaN     300
5555      125      131  ...    NaN      NaN     NaN     NaN    NaN     300
5556      125      164  ...    NaN      NaN     NaN     NaN    NaN     300

      DENRD20  DLEVD20  CONIND20 REGIND20
0         NaN      NaN       NaN      NaN
1         NaN      NaN       NaN      NaN
2         NaN      NaN       NaN      NaN
3         NaN      NaN       NaN      NaN
4         NaN      NaN       NaN      NaN
...       ...      ...       ...      ...
5552      NaN      NaN       NaN      NaN
5553      NaN      NaN       NaN      NaN
5554      NaN      NaN       NaN      NaN
5555      NaN      NaN       NaN      NaN
5556      NaN      NaN       NaN      NaN

[5557 rows x 392 columns]

file16.csv
      YEAR   RECNO  SCHOOL  SBOARD  REGBOARD  CNTYBOARD  GEND  BIRTHY  \
0     2016  831469   10523    7056    6029.0     5029.0   120    1997
1     2016  831461   11120    7007    6013.0     5013.0   120    1996
2     2016  831454   10613    7055    6024.0     5024.0   120    1997
3     2016  831385   10316    7027    6014.0     5014.0   120    1998
4     2016  831384   11188    7020    6007.0     5007.0   120    1998
...    ...     ...     ...     ...       ...        ...   ...     ...
5451  2016  800026   10342    7007    6013.0     5013.0   120    1998
5452  2016  800047   11199    7010    6032.0     5032.0   119    1998
5453  2016  800676   10702    7048    6012.0     5012.0   120    1998
5454  2016  800663   10413    7021    6031.0     5031.0   119    1998
5455  2016  800630   11155    7007    6024.0     5024.0   120    1997

      RESPROV  RESCNTY  ... DMAJ20  DCOOP20  DLEV20  UDEC20  PRO20  PRGO20  \
0         125      161  ...    NaN      NaN     NaN     NaN    NaN     300
1         125      143  ...    NaN      NaN     NaN     NaN    NaN     300
2         125      156  ...    NaN      NaN     NaN     NaN    NaN     300
3         125      144  ...    NaN      NaN     NaN     NaN    NaN     300
4         125      137  ...    NaN      NaN     NaN     NaN    NaN     300
...       ...      ...  ...    ...      ...     ...     ...    ...     ...
5451      125      143  ...    NaN      NaN     NaN     NaN    NaN     300
5452      125      164  ...    NaN      NaN     NaN     NaN    NaN     300
5453      125      142  ...    NaN      NaN     NaN     NaN    NaN     300
5454      125      163  ...    NaN      NaN     NaN     NaN    NaN     300
5455      125      156  ...    NaN      NaN     NaN     NaN    NaN     300

      DENRD20  DLEVD20  CONIND20 REGIND20
0         NaN      NaN       NaN      NaN
1         NaN      NaN       NaN      NaN
2         NaN      NaN       NaN      NaN
3         NaN      NaN       NaN      NaN
4         NaN      NaN       NaN      NaN
...       ...      ...       ...      ...
5451      NaN      NaN       NaN      NaN
5452      NaN      NaN       NaN      NaN
5453      NaN      NaN       NaN      NaN
5454      NaN      NaN       NaN      NaN
5455      NaN      NaN       NaN      NaN

[5456 rows x 392 columns]

file17.csv
      YEAR   RECNO  SCHOOL  SBOARD  REGBOARD  CNTYBOARD  GEND  BIRTHY  \
0     2017  831470   11140    7007    6013.0     5013.0   120    1999
1     2017  831467   11140    7007    6013.0     5013.0   120    1998
2     2017  831449   11219    7010    6007.0     5007.0   120    1998
3     2017  831463   10297    7034    6028.0     5028.0   120    1998
4     2017  831462   11219    7010    6007.0     5007.0   120    1999
...    ...     ...     ...     ...       ...        ...   ...     ...
5202  2017  800663   10995    7010    6032.0     5032.0   120    1998
5203  2017  800670   10698    7053    6013.0     5013.0   120    1998
5204  2017  800661   10290    7020    6007.0     5007.0   120    1998
5205  2017  800636   10532    7007    6013.0     5013.0   120    2001
5206  2017  800628   10685    7045    6016.0     5016.0   119    1998

      RESPROV  RESCNTY  ... DMAJ20  DCOOP20  DLEV20  UDEC20  PRO20  PRGO20  \
0         125      143  ...    NaN      NaN     NaN     NaN    NaN     300
1         125      143  ...    NaN      NaN     NaN     NaN    NaN     300
2         125      137  ...    NaN      NaN     NaN     NaN    NaN     300
3         125      160  ...    NaN      NaN     NaN     NaN    NaN     300
4         125      137  ...    NaN      NaN     NaN     NaN    NaN     300
...       ...      ...  ...    ...      ...     ...     ...    ...     ...
5202      125      164  ...    NaN      NaN     NaN     NaN    NaN     300
5203      125      143  ...    NaN      NaN     NaN     NaN    NaN     300
5204      125      137  ...    NaN      NaN     NaN     NaN    NaN     300
5205      125      143  ...    NaN      NaN     NaN     NaN    NaN     300
5206      125      146  ...    NaN      NaN     NaN     NaN    NaN     300

      DENRD20  DLEVD20  CONIND20 REGIND20
0         NaN      NaN       NaN      NaN
1         NaN      NaN       NaN      NaN
2         NaN      NaN       NaN      NaN
3         NaN      NaN       NaN      NaN
4         NaN      NaN       NaN      NaN
...       ...      ...       ...      ...
5202      NaN      NaN       NaN      NaN
5203      NaN      NaN       NaN      NaN
5204      NaN      NaN       NaN      NaN
5205      NaN      NaN       NaN      NaN
5206      NaN      NaN       NaN      NaN

[5207 rows x 392 columns]

In [79]:
## Loading preprocessed dataframes
pklFiles = [f for f in os.listdir("pickles/") if f.split('1')[0] == 'file']
for file in pklFiles:
	df = load_pkl("pickles/" + file)
	print(df.shape)

(3979, 392)
(3958, 392)
(4286, 392)
(4638, 392)
(4836, 392)
(5557, 392)
(5456, 392)
(5207, 392)

# Change this 'fname' value to load data for different years

In [87]:
# YEAR:
fname = "file16.pkl"
df = load_pkl("pickles/"+fname)

### Starting to analyze the data

In [107]:
# First 30 columns:
firstPart = df.iloc[:,0:30]
# print(firstPart.columns.values)

# Columns 30 to 65: (top 6 course marks)
top6CourseMarks = df.iloc[:,30:66]
# print(top6CourseMarks.columns.values)

cols = []
for column in top6CourseMarks[top6CourseMarks.columns[2::3]]:
    cols.append(df[column])
hstack = pd.concat([x for x in cols], axis=1)
# hstack.fillna(0, inplace=True)
hstack['Sum'] = hstack.mean(axis=1)
print(hstack)

# Columns 66 to 71:
middle = df.iloc[:,66:72]
print(middle["WAVERG1"], middle["WAVERG2"])
# print(middle.columns.values)

# Columns 72 to 391:
choices = df.iloc[:, 72:]
# print(choices.columns.values)

      SECORM1  SECORM2  SECORM3  SECORM4  SECORM5  SECORM6  SECORM7  SECORM8  \
0        93.0     95.0     91.0     87.0     88.0     88.0     87.0     85.0
1        72.0     88.0     95.0     90.0     94.0     80.0     95.0      NaN
2        71.0     66.0     70.0     71.0     67.0     81.0     82.0      NaN
3        83.0     94.0     94.0     90.0     87.0     92.0      NaN      NaN
4        91.0     93.0     96.0     95.0     96.0     93.0      NaN      NaN
...       ...      ...      ...      ...      ...      ...      ...      ...
5451      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN
5452     87.0     90.0     77.0     80.0     81.0     87.0      NaN      NaN
5453     95.0     91.0     88.0     78.0     75.0     96.0     91.0     85.0
5454     60.0     51.0     77.0     86.0     77.0     86.0     80.0     85.0
5455     68.0     75.0     82.0      NaN     84.0     76.0     70.0      NaN

      SECORM9  SECORM10  SECORM11  SECORM12        Sum
0        85.0       NaN       NaN       NaN  88.777778
1         NaN       NaN       NaN       NaN  87.714286
2         NaN       NaN       NaN       NaN  72.571429
3         NaN       NaN       NaN       NaN  90.000000
4         NaN       NaN       NaN       NaN  94.000000
...       ...       ...       ...       ...        ...
5451      NaN       NaN       NaN       NaN        NaN
5452      NaN       NaN       NaN       NaN  83.666667
5453     93.0       NaN       NaN       NaN  88.000000
5454      NaN       NaN       NaN       NaN  75.250000
5455      NaN       NaN       NaN       NaN  75.833333

[5456 rows x 13 columns]
0         0
1         0
2       737
3       900
4       940
       ...
5451      0
5452    837
5453    923
5454    785
5455      0
Name: WAVERG1, Length: 5456, dtype: int64 0       903
1       903
2       737
3       900
4       940
       ...
5451      0
5452    837
5453    923
5454    818
5455    758
Name: WAVERG2, Length: 5456, dtype: int64

In [89]:
# # COlumns 72 to 391:
# choices = df.iloc[:, 72:]
# print(choices.columns.values)
# for col in choices.columns.values:
#     print[]
    
# cols = []
# for column in top6CourseMarks[top6CourseMarks.columns[2::3]]:
#     cols.append(df[column])
# hstack = pd.concat([x for x in cols], axis=1)
# # hstack.fillna(0, inplace=True)
# hstack['Sum'] = hstack.mean(axis=1)
# print(hstack)

# TODOS:
- Determine the cutoff by finding lowest GPA student that got into Mac program
- Group choices for each student
- Divide dataset into those who got into Mac, and those who did not.

# Determining grade cutoff

### Seperating relevant data
- Splitting data into students who accept and offer from mac and those who don't.
- Isolating 8 initial columns of interest for analysis

In [102]:
## Starting columns of interest:
# RESPROV - Province of Residence
# RESCNTY - County of Residence
# ZIP3 - Residence Postal Code (First 3 Digits)
# CONFUNI - Confirmed University (OurUni='196')
# CONFPR - Confirmed Program (OurProg='SI', OurProg_coop='SIA')
# CONFCHOIC - OUAC Confirmed Choice Preference
# WAVERG1 - Weighted Average (best 6 OAC / Senior Level current year finals)
# WAVERG2 - Weighted Average (best 6 OAC / Senior Level all year finals)
## First 6 columns are in first half, last 2 are in "Middle" dataframe.

COIsFirstHalf = ["RESPROV", "RESCNTY", "ZIP3", "CONFUNI", "CONFPR", "CONFCHOIC"]
COIsSecondHalf = ["WAVERG1", "WAVERG2"]

# Adding columns of interest found in first half of the data
columnsOfInterest = pd.concat([firstPart[x] for x in COIsFirstHalf], axis=1)

# Adding the rest of the columns of interest
columnsOfInterest = pd.concat([columnsOfInterest] + [middle[x] for x in COIsSecondHalf],axis=1)
copy = columnsOfInterest.copy()

mcmasterVector = copy["CONFUNI"] == 196
notmcmasterVector = copy["CONFUNI"] != 196

In [106]:
# Students that received and accepted a McMaster offer:
acceptedMcMaster = copy[mcmasterVector]
# print(acceptedMcMaster)
# print(acceptedMcMaster[(acceptedMcMaster["WAVERG2"] > 0) & (acceptedMcMaster["CONFPR"] == "SIA")].min())
print("Students who accepted an offer from McMaster:")
print("Mean values for each column:")
print(acceptedMcMaster[(acceptedMcMaster["WAVERG2"] > 0) & (acceptedMcMaster["CONFPR"] == "SIA")].mean())
print("\nMax values for each column:")
print(acceptedMcMaster[(acceptedMcMaster["WAVERG2"] > 0) & (acceptedMcMaster["CONFPR"] == "SIA")].max())
print("\nLowest 5 weighted average:")
print(acceptedMcMaster[(acceptedMcMaster["WAVERG2"] > 0) & (acceptedMcMaster["CONFPR"] == "SI")].nsmallest(5,"WAVERG2"))
print("\nShape of acceptedMcMaster df (number of students that accepted):")
print(acceptedMcMaster.shape)

# Students that didn't accept a mcmaster offer:
print('\n\n\n\n')
notMcMaster = copy[notmcmasterVector]
# print(notMcMaster)
print("Min average of students who didn't accept mac offer")
print(notMcMaster[notMcMaster["WAVERG2"] > 0].min())
print("\nMax average of students who didn't accept mac offer")
print(notMcMaster[notMcMaster["WAVERG2"] > 0].max())
print("\nAverage average of students who didn't accept mac offer")
print(notMcMaster[notMcMaster["WAVERG2"] > 0].mean())

Students who accepted an offer from McMaster:
Mean values for each column:
RESPROV      124.977901
RESCNTY      149.314917
CONFUNI      196.000000
CONFCHOIC      2.217311
WAVERG1      721.955801
WAVERG2      910.149171
dtype: float64

Max values for each column:
RESPROV      125
RESCNTY      185
CONFUNI      196
CONFPR       SIA
CONFCHOIC     10
WAVERG1      988
WAVERG2      990
dtype: object

Lowest 5 weighted average:
      RESPROV  RESCNTY ZIP3  CONFUNI CONFPR  CONFCHOIC  WAVERG1  WAVERG2
5373      125      144  M7A    196.0     SI        2.0      858      858
4588      125      143  N7Q    196.0     SI        3.0      860      860
135       125      165  M3B    196.0     SI        1.0      825      862
299       125      146  M7I    196.0     SI        1.0      867      867
4066      125      146  M7K    196.0     SI        1.0      867      867

Shape of acceptedMcMaster df (number of students that accepted):
(943, 8)





Min average of students who didn't accept mac offer
RESPROV      121.0
RESCNTY      134.0
CONFUNI      103.0
CONFCHOIC      1.0
WAVERG1        0.0
WAVERG2      557.0
dtype: float64

Max average of students who didn't accept mac offer
RESPROV      125.0
RESCNTY      185.0
CONFUNI      199.0
CONFCHOIC     30.0
WAVERG1      997.0
WAVERG2      998.0
dtype: float64

Average average of students who didn't accept mac offer
RESPROV      124.913543
RESCNTY      149.141412
CONFUNI      187.062866
CONFCHOIC      2.743955
WAVERG1      693.652334
WAVERG2      878.493217
dtype: float64